couchdb: {
    hostname: localhost,
    port: 5984,
    database: melkman,
}

amqp: {
    hostname: localhost,
    port: 5672,
    virtual_host: melkman,
    userid: melkman,
    password: melkman,
}

pubsubhubbub_client: {
    host: 0.0.0.0, # accept remote requests
    port: 8080,
    callback_url: "http://yourdomain.com:8080/",
}

plugins:
    - pattern: melkman.*
      enabled: true
    - pattern: melkman.fetch.pubsubhubbub.*
      enabled: false
